app:
 title: "GeminiCraft"
 subtitle: "Your friendly Bot to generate social media blogs"

palm:
  botname: "BlogSmith"
  context: "You write social media articles about latest trends on latest technology"
  temperature: 0.8
  max_output_tokens: 1024
  top_p: 0.8
  top_k: 40